### ISSUE TITLE
[Spark Databricks] Is OpenLineage compatible with hive metastore and Unity Catalog?

### ISSUE THREAD

**Issue by rodrigo-maia-manta** [OpenLineage/OpenLineage#2121]
Hello.
I'm testing open lineage for data bricks using spark/pyspark and trying simple notebook operations such as reading from a table (hive_metastore/Unity Catalog), dropping some columns, and writing to a new table.

The code works fine and data is created as expected. When I check the logs for the open lineage json payload, i cant find anything related to the output. Besides, a simple operation is generating MBs of logs. For this example, this operation generated almost 10MB of logs

_Sample Code:_
`val df = spark.read.table("rodrigo.default.countries")`
`df.write.mode("overwrite").saveAsTable("rodrigo.default.countries_test03")`

OR

`val df = spark.read.table("countries")`
`df.write.mode("overwrite").saveAsTable("countries_test03")`

The JSON payload has no outputs for this operation. Only Inputs. 

Besides, the following error is found in the logs:
`PlanUtils: apply method failed with
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.plans.logical.ReplaceTableAsSelect.tableSpec()Lorg/apache/spark/sql/catalyst/plans/logical/TableSpec; at io.openlineage.spark33.agent.lifecycle.plan.CreateReplaceDatasetBuilder.lambda$apply$3(CreateReplaceDatasetBuilder.java:118)`

I was wondering if it has anything to do with the hive_metastore or the Unity Catalog.

_Databricks Cluster_
- Spark: 3.4.1
- Scala: 2.12
- OpenLinegae:1.1.0

_Configs:_
`spark.openlineage.transport.type console`
`spark.extraListeners io.openlineage.spark.agent.OpenLineageSparkListener`
`spark.openlineage.version v1`

Jar: openlineage-spark-1.1.0.jar

[log4j-active.log](https://github.com/OpenLineage/OpenLineage/files/12676594/log4j-active.log)

**Comment by pawel-big-lebowski** [comment]
Hi @rodrigo-maia-manta, we do have an integration test for verifying behaviour of openlineage-spark on databricks: 

https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/app/src/test/java/io/openlineage/spark/agent/DatabricksIntegrationTest.java

What it looks like from the logs you provided, a command class `ReplaceTableAsSelect` has different implementation on Databricks runtime. We should create an issue for that.

**Comment by rodrigo-maia-manta** [comment]
Hello There, @pawel-big-lebowski  To add to this issue:

- I've tested OL 1.3.1 and 1.4.1 and the issue remains.
- I've also enabled debug facets to gather as much information as possible and here is the result:

---------- 
```JSON
"classpath": {
                    "openLineageVersion": "1.4.1",
                    "sparkVersion": "3.4.1",
                    "scalaVersion": "2.12.15",
                    "jars": [],
                    "classDetails": [
                        {
                            "className": "org.apache.spark.sql.delta.catalog.DeltaCatalog",
                            "onClasspath": true
                        },
                        {
                            "className": "org.apache.iceberg.catalog.Catalog",
                            "onClasspath": false
                        },
                        {
                            "className": "com.google.cloud.spark.bigquery.BigQueryRelation",
                            "packageVersion": "0.22.2-SNAPSHOT",
                            "onClasspath": true
                        }
                    ]
                },
```
---------- 
```JSON
"logicalPlan": {
                    "nodes": [
                        {
                            "id": "ReplaceTableAsSelect@547733906",
                            "desc": "ReplaceTableAsSelect TableSpec(Map(),Some(delta),Map(),None,None,None,false,Set(),None,None,None), true, true\n   :- ResolvedIdentifier com.databricks.sql.managedcatalog.UnityCatalogV2Proxy@7de42c6e, default.universities_country_test300\n   +- Project [university_name#169, country_name#171]\n      +- Project [id#167L AS university_id#161L, university_name#169, country_name#171]\n         +- Join Inner, (country_id#168L = id#170L)\n            :- SubqueryAlias hive_metastore.default.universities\n            :  +- Relation hive_metastore.default.universities[id#167L,country_id#168L,university_name#169] parquet\n            +- SubqueryAlias hive_metastore.default.countries\n               +- Relation hive_metastore.default.countries[id#170L,country_name#171] parquet\n",
                            "children": []
                        }
                    ]
                }
```

[metadata.json](https://github.com/OpenLineage/OpenLineage/files/12856573/metadata.json)
As you can see, no output is generated at all.

**Is there any other test I could perform to contribute to this issue?**

The test notebook :
![image](https://github.com/OpenLineage/OpenLineage/assets/144318068/c0a28c36-ed56-4230-9db4-24c7e02a6a86)

The log for NoSuchMethodError:
![image](https://github.com/OpenLineage/OpenLineage/assets/144318068/093b6ef6-77f8-4ee6-b047-03bfdc729041)

**Comment by pawel-big-lebowski** [comment]
It's working on `13.0.x-scala2.12`, but it's not working anymore on `13.3.x-scala2.12` because of this definition changed: https://github.com/apache/spark/blob/v3.5.0/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/v2Commands.scala#L522

Looks like they released within 13.3 catalyst from spark 3.5.

**Comment by pawel-big-lebowski** [comment]
Is this still a valid issue? I think it should have been solved within: https://github.com/OpenLineage/OpenLineage/pull/2185

**Comment by rodrigo-maia-manta** [comment]
Unfortunately, it is. I still can't manage to capture output lineage from UC with OL 1.5. Input is Ok.

**Comment by ppalka-lingaro** [comment]
is there any special setup for unity catalog, or default spark
I need lineage to be visable in purview, I have the accelarator configured but it doesn't support UC as per default config
https://openlineage.io/blog/openlineage-microsoft-purview#what-is-microsoft-purview

any advise

**Comment by mobuchowski** [comment]
I don't think we do anything specifically for Unity Catalog in Spark integration. Something probably needs to be done to make it work - we happily accept contributions 🙂

**Comment by rodrigo-maia-manta** [comment]
how can i start helping with that?

**Comment by albanovito** [comment]
I have the same error with Databricks Runtime  DBR: 15.4 LTS (includes Apache Spark 3.5.0, Scala 2.12). I think the problem is the interaction with Databricks catalog, because the event not contains the output information.  Any news?

```
25/04/08 15:12:26  INFO PlanUtils: apply method failed with
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at com.databricks.sql.managedcatalog.ManagedCatalogCommon.intraQueryCatalogCachingEnabled(ManagedCatalogCommon.scala:294)
	at com.databricks.sql.managedcatalog.ManagedCatalogCommon.$anonfun$getTable$4(ManagedCatalogCommon.scala:1067)
	at scala.Option.getOrElse(Option.scala:189)
	at com.databricks.sql.managedcatalog.ManagedCatalogCommon.getTable(ManagedCatalogCommon.scala:1058)
	at com.databricks.sql.managedcatalog.ManagedCatalogCommon.getTableRawMetadata(ManagedCatalogCommon.scala:1086)
	at com.databricks.sql.managedcatalog.NonPermissionEnforcingManagedCatalog.super$getTableRawMetadata(NonPermissionEnforcingManagedCatalog.scala:192)
	at com.databricks.sql.managedcatalog.NonPermissionEnforcingManagedCatalog.$anonfun$getTableRawMetadata$1(NonPermissionEnforcingManagedCatalog.scala:193)
	at com.databricks.sql.managedcatalog.NonPermissionEnforcingManagedCatalog.withDbInternalCatalogErrorHandling(NonPermissionEnforcingManagedCatalog.scala:220)
	at com.databricks.sql.managedcatalog.NonPermissionEnforcingManagedCatalog.getTableRawMetadata(NonPermissionEnforcingManagedCatalog.scala:192)
	at com.databricks.sql.managedcatalog.ProfiledManagedCatalog.$anonfun$getTableRawMetadata$1(ProfiledManagedCatalog.scala:219)
	at org.apache.spark.sql.catalyst.MetricKeyUtils$.measure(MetricKey.scala:1181)
	at com.databricks.sql.managedcatalog.ProfiledManagedCatalog.$anonfun$profile$1(ProfiledManagedCatalog.scala:63)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at com.databricks.sql.managedcatalog.ProfiledManagedCatalog.profile(ProfiledManagedCatalog.scala:62)
	at com.databricks.sql.managedcatalog.ProfiledManagedCatalog.getTableRawMetadata(ProfiledManagedCatalog.scala:219)
	at com.databricks.sql.managedcatalog.ManagedCatalogSessionCatalog.getTableRawMetadataFromMetastore(ManagedCatalogSessionCatalog.scala:1372)
	at com.databricks.sql.managedcatalog.ManagedCatalogSessionCatalog.getTableRawMetadata(ManagedCatalogSessionCatalog.scala:1342)
	at com.databricks.sql.DatabricksSessionCatalog.getTableRawMetadata(DatabricksSessionCatalog.scala:84)
	at com.databricks.sql.DatabricksSessionCatalog.getTableMetadata(DatabricksSessionCatalog.scala:95)
	at org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog.$anonfun$loadTable$1(V2SessionCatalog.scala:93)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.execution.datasources.v2.V2SessionCatalog.loadTable(V2SessionCatalog.scala:92)
	at org.apache.spark.sql.connector.catalog.DelegatingCatalogExtension.loadTable(DelegatingCatalogExtension.java:77)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog.super$loadTable(DeltaCatalog.scala:376)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog.$anonfun$loadTable$1(DeltaCatalog.scala:376)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile(DeltaLogging.scala:316)
	at com.databricks.sql.transaction.tahoe.metering.DeltaLogging.recordFrameProfile$(DeltaLogging.scala:314)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog.recordFrameProfile(DeltaCatalog.scala:121)
	at com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog.loadTable(DeltaCatalog.scala:375)
	at com.databricks.sql.managedcatalog.UnityCatalogV2Proxy.loadTable(UnityCatalogV2Proxy.scala:212)
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.AbstractDatabricksHandler.getDatasetIdentifier(AbstractDatabricksHandler.java:91)
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.lambda$getDatasetIdentifier$2(CatalogUtils3.java:61)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:536)
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:63)
	at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetIdentifier(CatalogUtils3.java:46)
	at io.openlineage.spark3.agent.utils.PlanUtils3.getDatasetIdentifier(PlanUtils3.java:51)
	at io.openlineage.spark35.agent.lifecycle.plan.CreateReplaceOutputDatasetBuilder.apply(CreateReplaceOutputDatasetBuilder.java:153)
	at io.openlineage.spark35.agent.lifecycle.plan.CreateReplaceOutputDatasetBuilder.lambda$apply$3(CreateReplaceOutputDatasetBuilder.java:125)
	at java.util.Optional.map(Optional.java:215)
	at io.openlineage.spark35.agent.lifecycle.plan.CreateReplaceOutputDatasetBuilder.apply(CreateReplaceOutputDatasetBuilder.java:123)
	at io.openlineage.spark35.agent.lifecycle.plan.CreateReplaceOutputDatasetBuilder.apply(CreateReplaceOutputDatasetBuilder.java:69)
	at io.openlineage.spark35.agent.lifecycle.plan.CreateReplaceOutputDatasetBuilder.apply(CreateReplaceOutputDatasetBuilder.java:43)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.apply(AbstractQueryPlanDatasetBuilder.java:97)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder$1.apply(AbstractQueryPlanDatasetBuilder.java:86)
	at io.openlineage.spark.agent.util.PlanUtils.safeApply(PlanUtils.java:315)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.lambda$apply$0(AbstractQueryPlanDatasetBuilder.java:76)
	at java.util.Optional.map(Optional.java:215)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:68)
	at io.openlineage.spark.api.AbstractQueryPlanDatasetBuilder.apply(AbstractQueryPlanDatasetBuilder.java:40)
	at io.openlineage.spark.agent.util.PlanUtils.safeApply(PlanUtils.java:315)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$buildDatasets$29(OpenLineageRunEventBuilder.java:396)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildOutputDatasets(OpenLineageRunEventBuilder.java:350)
	at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:201)
	at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:144)
	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecEnd$2(OpenLineageSparkListener.java:149)
	at io.openlineage.client.circuitBreaker.NoOpCircuitBreaker.run(NoOpCircuitBreaker.java:27)
	at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:146)
	at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:121)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:104)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:41)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:41)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:199)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:169)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:115)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:115)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:110)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:106)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1643)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:106)
```

**Comment by mobuchowski** [comment]
@albanovito does the table exists when the exception happens?

**Comment by albanovito** [comment]
> [@albanovito](https://github.com/albanovito) does the table exists when the exception happens?

Yes, it does. The table exists and the job completes successfully. The event in the log contains all the data except the output. Another strange thing is that the log level is info and not error

**Comment by rupert-the-evill-one** [comment]
@albanovito can confirm the same behaviour on databricks... very frustrating

**Comment by luke-hoffman1** [comment]
@arturowczarek , does #3674 fix this?
